apiVersion: v1
kind: Pod
metadata:
  labels:
    app: prometheus
    pod-template-hash: 778588f7bf
  name: prometheus-778588f7bf-ltrvt
  namespace: observability
spec:
  containers:
  - args:
    - --config.file=/etc/prometheus/prometheus.yml
    image: prom/prometheus:latest
    imagePullPolicy: Always
    name: prometheus
    ports:
    - containerPort: 9090
      protocol: TCP
    volumeMounts:
    - mountPath: /etc/prometheus/
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vkvm5
      readOnly: true
  nodeName: aks-nodepool1-14987286-vmss000001

  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: prometheus-config
    name: config-volume
  - name: kube-api-access-vkvm5
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
